### ISSUE TITLE
We don't know how to parse this version of SAST report

### ISSUE THREAD

**Issue by frakman1** [pcfens/sast-parser#2]
I tried using this against a `gl-sast-report.json` file from the latest Gitlab v14.8.2 and it was unable to parse it.
I've included the file for reference. It's getting tripped up on this line:
` "version": "14.0.4",`
[gl-sast-report.json.txt](https://github.com/pcfens/sast-parser/files/8157458/gl-sast-report.json.txt)

**Comment by mbyrne00** [comment]
@frakman1 - just comment out these lines and it still seems to work for me. Obviously it may miss some new features in the schema

```
        if StrictVersion(data['version']) >= StrictVersion("9.0"):
            print('We don\'t know how to parse this version of SAST report')
            sys.exit(1)
```

**Comment by gimli2** [comment]
> @frakman1 - just comment out these lines ...
Thank you for that idea, it helped.
