### ISSUE TITLE
Docker image broken?

### ISSUE THREAD

**Issue by FrancYescO** [pcfens/sast-parser#4]
can you give an example usage?

```
docker run --rm -v $(pwd)/gl-sast-report.json:/gl-sast-report.json pcfens/sast-parser /gl-sast-report.json
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/gl-sast-report.json": permission denied: unknown.
```

maybe CMD in dockerfile should be replaced in ENTRYPOINT

also looks the image on dockerhub is not updated as is from 2 years ago

**Comment by HeavenSleep** [comment]
I made a PR (#6) that could solve your problem

**Comment by pcfens** [comment]
After merging #6 I pushed the latest image to the Docker Hub (I need to setup automated builds)

**Comment by HeavenSleep** [comment]
@pcfens I already did the automated build, 'im going to open a new PR

**Comment by HeavenSleep** [comment]
@pcfens done in #7
